### ISSUE TITLE
Méthode ne respectant pas le code de conduite de nommage

### ISSUE THREAD

**Issue by StagramTG** [gnikwo/LORE#2]
https://github.com/gnikwo/LORE/blob/d377c8095eec33c1a471564cabba885a5ec75e64/Lore/src/Camera.cpp#L161

Cette méthode se doit d'être renommée... Je propose "setDirection" ou "orientate" (Je préfère le premier) !
Bonne chance pour ce chantier colossal de renommage 😝 🎉

**Comment by nab-os** [comment]
Merci de ta remarque, c'est maintenant corrigé.
N'hésite pas à relire les modifications qui ont été apportées. ;) <3
